version: '3'
services:
    redis:
        image: redis:4.0.6-alpine
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
          - "6379:6379"
        volumes:
            - ./redis:/redis

    flask-app:
        image: messages.prepwithmo
        #container_name: messages.prepwithmo
        build:
          context: .
          dockerfile: Dockerfile.Service.Production

        extra_hosts:
            - "host:192.168.1.135"

        restart: always
        ports:
            - '5003:5003'
        volumes:
            - ./app:/app

    worker:
        image: dblistener.messages.prepwithmo
        build:
            context: .
            dockerfile: Dockerfile.Worker.Production
        depends_on:
            - redis
        extra_hosts:
            - "host:192.168.1.135"
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        command: rq worker --url redis://:${REDIS_PASSWORD}@redis:6379
        links:
            - redis
