version: '3'
services:
    redis:
        image: redis:4.0.6-alpine
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
          - "6379:6379"
        volumes:
            - ./redis:/redis

    flask-app:
        image: messages.prepwithmo
        container_name: service.dblistener.prepwithmo
        build:
          context: .
          dockerfile: Dockerfile.Service.Development

#        extra_hosts:
#            - "redis:${DIGITAL_OCEAN_IP_ADDRESS}"#

        restart: always
        environment:
            - DBUSERNAME=${DBUSERNAME}
            - DBPASSWORD=${DBPASSWORD}
        ports:
            - '5003:5003'
        volumes:
            - /home/mobolaji00/dblistener.prepwithmo:/service-app

    worker:
        image: worker.dblistener.prepwithmo
        container_name: worker.dblistener.prepwithmo
        build:
            context: .
            dockerfile: Dockerfile.Worker.Development
        depends_on:
            - redis
        extra_hosts:
            - "redis:${DIGITAL_OCEAN_IP_ADDRESS}"#
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        volumes:
            - /home/mobolaji00/dblistener.prepwithmo:/worker-app
        command: >
            echo ${DIGITAL_OCEAN_IP_ADDRESS}
            && rq worker --url redis://:${REDIS_PASSWORD}@redis:6379
        links:
            - redis
